# Generated by Django 4.2 on 2023-04-30 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firm',
            name='creator',
        ),
    ]
