# Generated by Django 4.2 on 2023-05-03 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firms', '0002_alter_firmexpense_shift_alter_firmincome_shift'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firm',
            name='total_amount_given',
        ),
        migrations.RemoveField(
            model_name='firm',
            name='total_amount_purchased',
        ),
        migrations.RemoveField(
            model_name='firmexpense',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='firmexpense',
            name='to_firm',
        ),
        migrations.AddField(
            model_name='firmexpense',
            name='to_firm_income',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='firms.firmincome'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='firmexpense',
            name='from_pharmacy',
            field=models.BooleanField(default=True),
        ),
    ]
