# Generated by Django 4.2 on 2023-05-13 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtfrompharmacy',
            name='remaining_debt',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='debttopharmacy',
            name='remaining_debt',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
