# Generated by Django 4.2 on 2023-05-13 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debttopharmacy',
            name='remaining_debt',
        ),
    ]
