# Generated by Django 4.2 on 2023-05-06 08:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('debts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debtrepayfrompharmacy',
            name='from_pharmacy',
        ),
        migrations.AddField(
            model_name='debtrepayfrompharmacy',
            name='from_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='debt_repays', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='debttopharmacy',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
