# Generated by Django 4.2 on 2023-05-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0002_debtfrompharmacy_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtfrompharmacy',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='debtrepayfrompharmacy',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='debtrepaytopharmacy',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='debttopharmacy',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
