# Generated by Django 4.2 on 2023-05-06 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
        ('debts', '0002_remove_debtrepayfrompharmacy_from_pharmacy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtfrompharmacy',
            name='transfer_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='general.transfermoneytype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='debtrepayfrompharmacy',
            name='transfer_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='general.transfermoneytype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='debtrepaytopharmacy',
            name='transfer_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='general.transfermoneytype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='debttopharmacy',
            name='transfer_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='general.transfermoneytype'),
            preserve_default=False,
        ),
    ]
