# Generated by Django 4.2 on 2023-05-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0003_remove_debtfrompharmacy_remaining_debt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtfrompharmacy',
            name='remaining_debt',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
