# Generated by Django 4.2 on 2023-05-13 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0004_debtfrompharmacy_remaining_debt'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtfrompharmacy',
            name='second_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='debtrepayfrompharmacy',
            name='second_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='debtrepaytopharmacy',
            name='second_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='debttopharmacy',
            name='second_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
