# Generated by Django 4.2 on 2023-05-05 04:30

import api.v1.apps.pharmacies.services
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=api.v1.apps.pharmacies.services.pharmacy_logo_upload_location)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('desc', models.TextField(blank=True, max_length=1000)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pharmacies', to='companies.company')),
            ],
            options={
                'verbose_name': 'Pharmacy',
                'verbose_name_plural': 'Pharmacies',
            },
        ),
    ]
