# Generated by Django 4.2 on 2023-04-29 11:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('firms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pharmacies', '0001_initial'),
        ('reports', '0001_initial'),
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacyExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('shift', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3)])),
                ('desc', models.CharField(blank=True, max_length=500)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('from_pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pharmacies.pharmacy')),
                ('income_expense_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='general.incomeexpensetype')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.report')),
                ('to_firm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='firms.firm')),
                ('to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacy_expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('shift', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3)])),
                ('desc', models.CharField(blank=True, max_length=500)),
                ('is_transfer', models.BooleanField(default=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('from_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to=settings.AUTH_USER_MODEL)),
                ('income_expense_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='general.incomeexpensetype')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.report')),
                ('to_firm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='firms.firm')),
                ('to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='income_expenses', to=settings.AUTH_USER_MODEL)),
                ('transfer_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='general.transfermoneytype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserExpenseHistory',
            fields=[
                ('userexpense_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='expenses.userexpense')),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('updater', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_expenses_history', to=settings.AUTH_USER_MODEL)),
                ('user_expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_expenses_history', to='expenses.userexpense')),
            ],
            options={
                'abstract': False,
            },
            bases=('expenses.userexpense',),
        ),
        migrations.CreateModel(
            name='PharmacyExpenseHistory',
            fields=[
                ('pharmacyexpense_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='expenses.pharmacyexpense')),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('pharmacy_expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_expenses_history', to='expenses.pharmacyexpense')),
                ('updater', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacy_expenses_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('expenses.pharmacyexpense',),
        ),
    ]
