# Generated by Django 4.2 on 2023-04-30 12:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_remove_company_is_active_alter_company_director'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='phone_number',
            new_name='phone_number1',
        ),
        migrations.AddField(
            model_name='client',
            name='company',
            field=models.ForeignKey(default=18, on_delete=django.db.models.deletion.PROTECT, to='companies.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='phone_number2',
            field=models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='Phone number must be entered in the format: "+998976543210". Up to 13 digits allowed.', regex='^[+]998\\d{9}$')]),
        ),
    ]
