version: "3.1"

services:
  postgres:
    image: postgres
    container_name: korkort_postgres
    restart: always

    environment:
      POSTGRES_DB: korkort_db
      POSTGRES_USER: user_korkort_db
      POSTGRES_PASSWORD: password_korkort_db
      PGDATA: /home/oybek/postgres/data
      POSTGRES_INITDB_ARGS: "-A md5"

    ports:
      - "54321:5432"
