# Generated by Django 4.2 on 2023-05-03 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debttopharmacy',
            name='is_paid',
        ),
        migrations.AddField(
            model_name='debttopharmacy',
            name='remaining_debt',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
