# Generated by Django 4.2 on 2023-05-03 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0002_remove_debttopharmacy_is_paid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debttopharmacy',
            name='remaining_debt',
        ),
    ]
