# Generated by Django 4.2 on 2023-05-03 07:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0003_remove_debttopharmacy_remaining_debt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtfrompharmacy',
            name='shift',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='debtrepayfrompharmacy',
            name='shift',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='debtrepaytopharmacy',
            name='shift',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='debttopharmacy',
            name='shift',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)]),
        ),
    ]
