# Generated by Django 4.2 on 2023-05-03 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0004_alter_debtfrompharmacy_shift_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debtrepayfrompharmacy',
            name='from_user',
        ),
        migrations.AlterField(
            model_name='debtrepayfrompharmacy',
            name='from_pharmacy',
            field=models.BooleanField(default=True),
        ),
    ]
