# Generated by Django 4.2 on 2023-05-03 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0005_remove_debtrepayfrompharmacy_from_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debtrepaytopharmacy',
            name='to_pharmacy',
        ),
    ]
