# Generated by Django 4.2 on 2023-05-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacyexpense',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='userexpense',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
