# Generated by Django 4.2 on 2023-05-13 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_alter_expensetype_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacyexpense',
            name='second_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userexpense',
            name='second_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
