# Generated by Django 4.2 on 2023-05-13 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(unique=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('total_amount_incomes', models.PositiveIntegerField(default=0)),
                ('total_amount_expenses', models.PositiveIntegerField(default=0)),
                ('total_amount_debt_trading', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
