# Generated by Django 4.2 on 2023-05-06 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
