# Generated by Django 4.2 on 2023-04-30 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmacy',
            name='is_active',
        ),
    ]
