# Generated by Django 4.2 on 2023-05-11 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incomes', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PharmacyIncomeHistory',
        ),
    ]
