# Generated by Django 4.2 on 2023-05-06 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
        ('incomes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmacyincome',
            name='is_transfer',
        ),
        migrations.AlterField(
            model_name='pharmacyincome',
            name='transfer_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='general.transfermoneytype'),
            preserve_default=False,
        ),
    ]
