# Generated by Django 4.2 on 2023-05-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomes', '0002_delete_pharmacyincomehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacyincome',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
