# Generated by Django 4.2 on 2023-05-06 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('incomes', '0002_remove_pharmacyincome_is_transfer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacyincome',
            name='to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pharmacy_incomes', to=settings.AUTH_USER_MODEL),
        ),
    ]
