# Generated by Django 4.2 on 2023-05-08 19:33

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('firms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firm',
            name='company',
        ),
        migrations.AddField(
            model_name='firm',
            name='director',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='firms', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='firmincome',
            name='deadline_date',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(datetime.date(2023, 5, 9))]),
        ),
        migrations.DeleteModel(
            name='FirmExpense',
        ),
    ]
