# Generated by Django 4.2 on 2023-05-06 06:31

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmincome',
            name='deadline_date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2023, 5, 6))]),
        ),
    ]
