# Generated by Django 4.2 on 2023-05-13 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmexpense',
            name='second_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='firmincome',
            name='second_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
