# Generated by Django 4.2 on 2023-05-06 11:10

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firms', '0002_alter_firmincome_deadline_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmincome',
            name='deadline_date',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(datetime.date(2023, 5, 6))]),
        ),
    ]
