# Generated by Django 4.2 on 2023-05-11 11:50

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firms', '0002_remove_firm_company_firm_director_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmincome',
            name='deadline_date',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(datetime.date(2023, 5, 11))]),
        ),
    ]
