# Generated by Django 4.2 on 2023-05-06 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firms', '0003_alter_firmincome_deadline_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FirmExpense',
        ),
    ]
