# Generated by Django 4.2 on 2023-05-07 07:37

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firms', '0004_delete_firmexpense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmincome',
            name='deadline_date',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(datetime.date(2023, 5, 7))]),
        ),
    ]
