# Generated by Django 4.2 on 2023-05-12 14:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0002_alter_pharmacy_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('general', '0004_alter_expensetype_director'),
        ('debts', '0003_alter_debtfrompharmacy_price_and_more'),
        ('reports', '0001_initial'),
        ('firms', '0004_alter_firmincome_deadline_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmincome',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.CreateModel(
            name='FirmExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('price', models.PositiveIntegerField()),
                ('shift', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)])),
                ('desc', models.CharField(blank=True, max_length=500)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_code', models.PositiveIntegerField()),
                ('verified_phone_number', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='Phone number must be entered in the format: "+998976543210". Up to 13 digits allowed.', regex='^[+]998\\d{9}$')])),
                ('verified_firm_worker_name', models.CharField(max_length=50)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('from_debt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='debts.debttopharmacy')),
                ('from_pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pharmacies.pharmacy')),
                ('from_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='firm_expenses', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.report')),
                ('to_firm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firms.firm')),
                ('transfer_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='general.transfermoneytype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
