# Generated by Django 4.2 on 2023-05-12 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firms', '0005_firmexpense'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FirmExpense',
        ),
    ]
