# Generated by Django 4.2 on 2023-05-12 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0001_initial'),
        ('firms', '0005_firmexpense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmexpense',
            name='from_pharmacy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='pharmacies.pharmacy'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='firmexpense',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='firmexpense',
            name='verified_firm_worker_name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='firmincome',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
