# Generated by Django 4.2 on 2023-05-12 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firms', '0006_alter_firmexpense_from_pharmacy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmexpense',
            name='verified_firm_worker_name',
            field=models.CharField(max_length=50),
        ),
    ]
