# Generated by Django 4.2 on 2023-05-08 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_alter_expensetype_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='expensetype',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='transfermoneytype',
            unique_together=set(),
        ),
    ]
